=== newtom69/FormationCSharp/ProjetXML/Agence.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="agence">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="vols" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="vols">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="vol" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  



  <xs:element name="vol">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="numero" />
        <xs:element ref="depart" />
        <xs:element ref="arrive" />
        <xs:element ref="escales" minOccurs="0" />
        <xs:element minOccurs="0" name="reservations">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="reservation">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="numero" type="xs:unsignedByte" />
                    <xs:element name="client">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="nom" type="xs:string" />
                          <xs:element name="prenom" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="civilite" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="statut" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="ouvert" />
            <xs:enumeration value="ferme" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="compagnie" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="numero">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="[A-Z]{2}[a-zA-Z0-9]{2,9}"></xs:pattern>  
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="depart">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="date" type="xs:date" use="required" />
          <xs:attribute name="horaire" type="xs:time" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="arrive">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="date" type="xs:date" use="required" />
          <xs:attribute name="horaire" type="xs:time" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="escales">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="escale" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="escale">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="heureArrive" type="xs:time" use="required" />
          <xs:attribute name="heureDepart" type="xs:time" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== newtom69/FormationCSharp/ProjetXML/Agence.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<?xml-stylesheet type="text/xsl" href= "Agence.xslt" ?>
<agence xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Agence.xsd">

  <vols>

    <vol statut="ouvert" compagnie="Air France">
      <numero>AF73632</numero>
      <depart date="2018-10-08" horaire="10:05:00">Lille</depart>
      <arrive date="2018-10-08" horaire="11:50:00">Nice</arrive>
      <reservations>
        <reservation>
          <numero>1</numero>
          <client civilite="homme">
            <nom>Abid</nom>
            <prenom>Jordan</prenom>
          </client>
        </reservation>
        <reservation>
          <numero>2</numero>
          <client civilite="homme">
            <nom>Vuille</nom>
            <prenom>Thomas</prenom>
          </client>
        </reservation>

      </reservations>
    </vol>

    <vol statut="ouvert" compagnie="Turkish Airlines">
      <numero>TA37800</numero>
      <depart date="2018-10-11" horaire="12:05:00">Paris</depart>
      <arrive date="2018-10-11" horaire="20:40:00">Ankara</arrive>
      <escales>
        <escale heureArrive="14:10:00" heureDepart="15:20:00">Rome</escale>
      </escales>
    </vol>

    <vol statut="ferme" compagnie="Lufthansa">
      <numero>LH2223</numero>
      <depart date="2018-09-13" horaire="08:05:00">Toulouse</depart>
      <arrive date="2018-09-14" horaire="02:45:00">Tokyo</arrive>
      <escales>
        <escale heureArrive="08:55:00" heureDepart="09:20:00">Munich</escale>
        <escale heureArrive="20:30:00" heureDepart="21:10:00">Hong Kong</escale>
      </escales>
    </vol>

    <vol statut="ouvert" compagnie="Lufthansa">
      <numero>LH28478489</numero>
      <depart date="2018-09-17" horaire="07:05:00">Toulouse</depart>
      <arrive date="2018-09-17" horaire="17:45:00">Ankara</arrive>
      <escales>
        <escale heureArrive="08:55:00" heureDepart="09:15:00">Paris</escale>
        <escale heureArrive="11:35:00" heureDepart="14:45:00">Rome</escale>
      </escales>
    </vol>

  </vols>
</agence>
